<?php
# This file was automatically generated by the MediaWiki 1.22.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
    exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "1.23.x";#"MediaWiki for Sae"
$wgMetaNamespace = "介绍信息";

$wgScriptExtension = '.php';

# Enable SSL Login && access full site
$wgServer = "//#{$_SERVER["HTTP_APPNAME"]}.sinaapp.com";
$wgSecureLogin = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";#zh-cn
$wgExtraLanguageNames = array();

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## Copyright  # 以下需要用户自行设置
$wgEnableCreativeCommonsRdf = true;
## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Site customization
# Query string length limit for ResourceLoader. 
$wgResourceLoaderMaxQueryLength = -1;

# End of automatically generated settings.
# Add more configuration options below.

/************************************************************************//**
 * @name   Script path settings
 */

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = '';
$wgArticlePath = "$wgScriptPath/$1";
$wgStylePath = "{$wgScriptPath}/skins";

## Database settings
$wgDBprefix = 'wiki_';
# http://www.mediawiki.org/wiki/Manual:DeleteOldRevisions.php

## Uploads
$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg' );
$wgThumbnailScriptPath = false;
$wgGenerateThumbnailOnParse = true;
$wgHashedUploadDirectory = true;

## Email settings
$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO
$wgEmergencyContact = 'wikiadmin@' . $serverName;//需要用户自行设置 ''
$wgPasswordSender   = 'apache@' . $serverName;//需要用户自行设置 ''
$wgEnotifUserTalk   = true; # UPO
$wgEnotifWatchlist  = true; # UPO
$wgAllowHTMLEmail   = false;
$wgEmailAuthentication = true;
# telnet smtp.gmail.com 587
# Gmail:
#
# $wgSMTP['gmail'] = array(
#   'smtp'     => 'smtp.gmail.com',
#   'port'     => '587',//465(ssl) 或 587(tls) 、25(ssl)
#   'tls'      => 'true',//用SSL连接, tls = ssl_v3
#   'username' => '...@gmail.com',
#   'password' => '...'
# );
# 
# QQ Email:
#
# $wgSMTP['qq'] = array(
#   'smtp'     => 'smtp.qq.com',
#   'port'     => '25',//465或587、25
#   'tls'      => 'false',//用SSL连接, tls = ssl_v3
#   'username' => '...@qq.com',
#   'password' => '...'
# );
# 
# $wgSMTP = $wgSMTP['qq'];
$wgSMTP = false;
## Email notification (Enotif) settings

## Access       # 默认只有注册用户才能编辑 
# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;

/************************************************************************//**
 * @name   Language, regional and character encoding settings
 */
## Localization
## Timezone settings
$wgLocaltimezone = 'Asia/Shanghai';

/************************************************************************//**
 * @name   User rights, access control and monitoring
 * 
 * Settings added to this array will override the default globals for the user
 * preferences used by anonymous visitors and newly created accounts.
 * For instance, to disable section editing links:
 * $wgDefaultUserOptions ['editsection'] = 0;
 */
$wgDefaultUserOptions = array(
    'ccmeonemails' => 0,
    'cols' => 80,
    'date' => 'default',
    'diffonly' => 0,
    'disablemail' => 0,
    'disablesuggest' => 0,
    'editfont' => 'default',
    'editondblclick' => 0,
    'editsection' => 1,
    'editsectiononrightclick' => 0,
    'enotifminoredits' => 0,
    'enotifrevealaddr' => 0,
    'enotifusertalkpages' => 1,
    'enotifwatchlistpages' => 0,
    'extendwatchlist' => 0,
    'fancysig' => 0,
    'forceeditsummary' => 0,
    'gender' => 'unknown',
    'hideminor' => 0,
    'hidepatrolled' => 0,
    'imagesize' => 2,
    'justify' => 0,
    'math' => 1,
    'minordefault' => 0,
    'newpageshidepatrolled' => 0,
    'nocache' => 0,
    'noconvertlink' => 0,
    'norollbackdiff' => 0,
    'numberheadings' => 0,
    'previewonfirst' => 0,
    'previewontop' => 1,
    'rcdays' => 7,
    'rclimit' => 50,#default:50, Special:ListFiles
    'rememberpassword' => 0,
    'rows' => 25,
    'searchlimit' => 20,
    'showhiddencats' => 0,
    'shownumberswatching' => 1,
    'showtoc' => 1,
    'showtoolbar' => 1,
    'skin' => false,
    'stubthreshold' => 0,
    'thumbsize' => 2,
    'underline' => 2,
    'uselivepreview' => 0,
    'usenewrc' => 0,
    'vector-simplesearch' => 1,
    'watchcreations' => 0,
    'watchdefault' => 0,
    'watchdeletion' => 0,
    'watchlistdays' => 3.0,
    'watchlisthideanons' => 0,
    'watchlisthidebots' => 0,
    'watchlisthideliu' => 0,
    'watchlisthideminor' => 0,
    'watchlisthideown' => 0,
    'watchlisthidepatrolled' => 0,
    'watchmoves' => 0,
    'wllimit' => 250,
    'useeditwarning' => 1,
    'prefershttps' => 1,
);
$wgQueryPageDefaultLimit = 50;

/************************************************************************//**
 * @name   Profiling, testing and debugging
 *
 * To enable profiling, edit StartProfiler.php
 */
$wgShowDebug = false;
$wgShowSQLErrors = $wgShowDebug;
$wgDebugComments = $wgShowDebug;
# like InnoDB ( not MyISAM ) : race lifecycle of the database transaction (opening, commit, rollback)
#$wgDebugDBTransactions = $wgShowDebug;
$wgDebugDumpSql = $wgShowDebug;
$wgDebugPrintHttpHeaders = $wgShowDebug;
$wgDebugRedirects = $wgShowDebug;
$wgDebugTimestamps = $wgShowDebug;
# other
$wgMemCachedDebug = $wgShowDebug;
$wgResourceLoaderDebug = $wgShowDebug;
$wgDebugTidy = $wgShowDebug;
# Profiling
$wgDebugFunctionEntry = $wgShowDebug;

/************************************************************************//**
 * @name   Extensions
 */
require_once( "$IP/extensions/SinaAppEngine/SinaAppEngine.php" );